# Generated by Django 3.2 on 2021-04-30 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0002_auto_20210426_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='topping',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
